global using MM_Guide_Programming_Aptitude.Question1;
global using MM_Guide_Programming_Aptitude.Question2;
global using MM_Guide_Programming_Aptitude.Question3;
global using MM_Guide_Programming_Aptitude.Question4;